# Generated by Django 4.0.6 on 2022-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('ICE', 'Instrumentation and Control Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('A', 'Architecture')], default='IT', max_length=3),
        ),
    ]
