# Generated by Django 4.0.6 on 2022-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='profilePic/'),
        ),
    ]
